name: JAM Auto Deploy to EC2

on:
  workflow_dispatch:
  push:
    branches: [ "main" ] 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR with Maven
        working-directory: ./jam
        run: mvn -B clean package -Dmaven.test.skip=true

      - name: Copy WAR to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 54.180.152.155
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY_JAM }}
          source: "jam/target/client-1.0.0-BUILD-SNAPSHOT.war"
          target: "/opt/tomcat/tomcat9/webapps/ROOT.war"
          strip_components: 0
          overwrite: true
          tar_tmp_path: ""
          tar_exec: ""

      - name: Restart Tomcat on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 54.180.152.155
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY_JAM }}
          script: |
            sudo /opt/tomcat/tomcat9/bin/shutdown.sh || true
            sleep 3
            sudo /opt/tomcat/tomcat9/bin/startup.sh
