name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true
      working-directory: ./jam

    - name: List WAR files
      run: ls -lh /home/runner/work/JAM/JAM/jam/target

    - name: Debug WAR path
      run: |
        echo "SEARCHING:"
        find /home/runner/work/JAM/JAM -name "*.war" -type f

    - name: Copy WAR file to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "jam/target/jam.war"
        target: "/home/ec2-user/tomcat/webapps/"
        overwrite: true

    - name: Restart Tomcat on EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          pkill -f tomcat || true
          mv /home/ec2-user/tomcat/webapps/jam.war /home/ec2-user/tomcat/webapps/ROOT.war
          cd /home/ec2-user/tomcat
          /home/ec2-user/tomcat/bin/startup.sh
